"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
format = '$all'

[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = '[âœ—](bold red)'

[hostname]
ssh_only = false
style = 'fg:#ff0000'
format = '[$ssh_symbol$hostname]($style) ğŸŒ '
disabled = false

[localip]
ssh_only = false
disabled = false

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 4
truncation_symbol = ''

[username]
style_user = 'blue bold'
format = '[$user]($style) ğŸ¯ '
disabled = false
show_always = true

[directory]
format = 'ó°‘¢ [$path]($style)[$read_only]($read_only_style) '
# truncate_to_repo = true
style = 'fg:#00bfff'
[conda]
disabled = false
format = '[$symbol$environment](dimmed green) '

[memory_usage]
disabled = false
threshold = -1
symbol = 'ğŸ'
style = 'fg:#228b22'
format = '$symbol [${ram}( )]($style) '

[time]
style = 'fg:#ffc0cb'
disabled = false
format = 'ğŸ•™[\[$time\]]($style) '
time_format = '%T'

[package]
format = 'ğŸ [$version](208 bold) '


[git_status]
conflicted = 'ğŸ³conflict'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“u2d'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“ modi'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[cmd_duration]
style = 'fg:#ff7f50'
min_time = 500
format = 'âœ¨ [$duration]($style)'
# ~/.config/starship.toml


# ~/.config/starship.toml

[container]
symbol = "ğŸ‹"
format = '[$symbol \[$name\]]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
